# Generated by Django 4.2.6 on 2023-10-26 09:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.CharField(max_length=200, verbose_name='Отделение')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отделы',
                'verbose_name_plural': 'Отделы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='./staticfiles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['xls', 'xlsx'])], verbose_name='Файлы')),
                ('date_upload', models.DateField(auto_now_add=True, verbose_name='За месяц')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='Провайдер')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Провайдера',
                'verbose_name_plural': 'Провайдеры',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.FloatField(verbose_name='Абонентская плата')),
            ],
            options={
                'verbose_name': 'Абон. плата',
                'verbose_name_plural': 'Абон. плата',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, verbose_name='Номер')),
                ('date_upload', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('payment', models.FloatField(verbose_name='Сумма')),
                ('result_pay', models.FloatField(verbose_name='Итог')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phonesapp.attachments', verbose_name='Отдел')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonesapp.files', verbose_name='Файл')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonesapp.providers', verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Номера парсера',
                'verbose_name_plural': 'Номера парсера',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, verbose_name='Номер')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('date_attach', models.DateField(blank=True, null=True, verbose_name='Дата прикрепления')),
                ('cf', models.BooleanField(default=False, verbose_name='ЦФ')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Активен')),
                ('attachment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='phonesapp.attachments', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Номера',
                'verbose_name_plural': 'Номера',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubscriptionFee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('summ', models.FloatField(verbose_name='Абонентская плата')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Абон. плата',
                'verbose_name_plural': 'historical Абон. плата',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProviders',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='Провайдер')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Активен')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Провайдера',
                'verbose_name_plural': 'historical Провайдеры',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalParser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(max_length=8, verbose_name='Номер')),
                ('date_upload', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('payment', models.FloatField(verbose_name='Сумма')),
                ('result_pay', models.FloatField(verbose_name='Итог')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('attachment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='phonesapp.attachments', verbose_name='Отдел')),
                ('file', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='phonesapp.files', verbose_name='Файл')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='phonesapp.providers', verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'historical Номера парсера',
                'verbose_name_plural': 'historical Номера парсера',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNumbers',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(max_length=8, verbose_name='Номер')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('date_attach', models.DateField(blank=True, null=True, verbose_name='Дата прикрепления')),
                ('cf', models.BooleanField(default=False, verbose_name='ЦФ')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Активен')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('attachment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='phonesapp.attachments', verbose_name='Отдел')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Номера',
                'verbose_name_plural': 'historical Номера',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFiles',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('file', models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(['xls', 'xlsx'])], verbose_name='Файлы')),
                ('date_upload', models.DateField(blank=True, editable=False, verbose_name='За месяц')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='phonesapp.providers', verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'historical Файлы',
                'verbose_name_plural': 'historical Файлы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAttachments',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('attachment', models.CharField(max_length=200, verbose_name='Отделение')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Активен')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Отделы',
                'verbose_name_plural': 'historical Отделы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='files',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonesapp.providers', verbose_name='Провайдер'),
        ),
    ]
