# Generated by Django 4.2.6 on 2023-10-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phonesapp.attachments', verbose_name='Отдел'),
        ),
    ]
